# -*- coding: utf-8 -*-
"""llm2605-mo1hw3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6_Iy7fjzp0OCtg_HIjm9u5m1d6Ztdg5

### 1. Environment and Data Preparation
In this section, we install dependencies, configure YandexGPT access, and download the dataset.
"""

# 
# !pip install requests pandas

import os
import json
import requests

# Configuration for YandexGPT
# Replace these with your actual credentials from Yandex Cloud
CATALOG_ID = 'your_catalog_id'
API_KEY = 'your_api_key'

# YandexGPT API Endpoint
URL = "https://llm.api.cloud.yandex.net/foundationModels/v1/completion"

import pandas as pd

def load_legal_docs(path='RuLegalNER/data/'):
    """Helper to load sample documents from CSV files using pandas."""
    docs = []
    if os.path.exists(path):
        for file in os.listdir(path):
            if file.endswith('.csv'):
                file_path = os.path.join(path, file)
                # Read CSV and take text from the first column
                df = pd.read_csv(file_path)
                if not df.empty:
                    # Extract text from the first column
                    texts = df.iloc[:, 0].dropna().astype(str).tolist()
                    for i, text in enumerate(texts):
                        docs.append({'filename': f"{file}_row_{i}", 'text': text})
    return docs

documents = load_legal_docs()
print(f'Loaded {len(documents)} documents.')
if documents:
    print(f'Sample length: {len(documents[0]["text"])} characters')

"""### 2. Text Preparation and Chunking
Since LLMs have context window limits, we implement a function to split long legal documents into smaller, manageable chunks.
"""

def chunk_text(text, max_chars=4000):
    """Splits text into chunks of maximum size."""
    return [text[i:i + max_chars] for i in range(0, len(text), max_chars)]

def prepare_documents(docs, max_chars=4000):
    """Prepares documents by checking length and chunking if necessary."""
    prepared_docs = []
    for doc in docs:
        text = doc['text']
        if len(text) > max_chars:
            chunks = chunk_text(text, max_chars)
            for i, chunk in enumerate(chunks):
                prepared_docs.append({
                    'filename': f"{doc['filename']}_part_{i}",
                    'text': chunk,
                    'original_length': len(text)
                })
        else:
            prepared_docs.append({
                'filename': doc['filename'],
                'text': text,
                'original_length': len(text)
            })
    return prepared_docs

# Apply preparation
processed_documents = prepare_documents(documents, 32000)
print(f'Total chunks/documents after processing: {len(processed_documents)}')
if processed_documents:
    print(f'Average chunk size: {sum(len(d["text"]) for d in processed_documents)/len(processed_documents):.0f} characters')